#!/usr/bin/env python3

import argparse
import pathlib

import numpy as np

def align_up(value, alignment):
    return (value + alignment - 1) // alignment * alignment

def c_array(array):
    return "{" + ", ".join(repr(float(x)) + "f" for x in array.flat) + "}"

def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("--m", type=int, required=True)
    parser.add_argument("--n", type=int, required=True)
    parser.add_argument("--k", type=int, required=True)
    parser.add_argument("--seed", type=int, default=42)
    parser.add_argument("--output", type=pathlib.Path, required=True)
    args = parser.parse_args()

    if min(args.m, args.n, args.k) <= 0:
        raise ValueError("M, N, and K must all be positive")

    mp = align_up(args.m, 16)
    npad = align_up(args.n, 16)
    kp = align_up(args.k, 8)
    rng = np.random.default_rng(args.seed)
    a = rng.standard_normal((args.m, args.k), dtype=np.float32)
    b = rng.standard_normal((args.k, args.n), dtype=np.float32)

    row = np.arange(args.m, dtype=np.int64)[:, None]
    col = np.arange(args.n, dtype=np.int64)[None, :]
    bias = (((row * 3 + col * 5) & 15) - 8).astype(np.float32) * 0.03125
    c = (a @ b).astype(np.float32) + bias

    ap = np.zeros((mp, kp), dtype=np.float32)
    bp = np.zeros((kp, npad), dtype=np.float32)
    biasp = np.zeros((mp, npad), dtype=np.float32)
    ap[:args.m, :args.k] = a
    bp[:args.k, :args.n] = b
    biasp[:args.m, :args.n] = bias

    apack = ap.reshape(mp // 16, 16, kp // 8, 8).transpose(0, 2, 3, 1).copy()
    bpack = bp.reshape(kp // 8, 8, npad // 16, 16).transpose(2, 0, 1, 3).copy()
    biaspack = biasp.reshape(mp // 16, 16, npad // 16, 16).transpose(
        0, 2, 1, 3).copy()

    text = f'''// Auto-generated by fp32-gemm-vle-vse/script/gen_data.py.
#include "layer.h"

static const vme_gemm_layer gemm_l = {{
    .M = {args.m}, .N = {args.n}, .K = {args.k},
    .Mp = {mp}, .Np = {npad}, .Kp = {kp},
}};

static const float gemm_Cref_dram[{args.m * args.n}]
    __attribute__((section(".dram"), aligned(64))) = {c_array(c)};

static const float gemm_Biaspack_dram[{mp * npad}]
    __attribute__((section(".dram"), aligned(64))) = {c_array(biaspack)};

static const float gemm_Apack_dram[{mp * kp}]
    __attribute__((section(".dram"), aligned(64))) = {c_array(apack)};

static const float gemm_Bpack_dram[{kp * npad}]
    __attribute__((section(".dram"), aligned(64))) = {c_array(bpack)};
'''
    args.output.parent.mkdir(parents=True, exist_ok=True)
    args.output.write_text(text)

if __name__ == "__main__":
    main()
