#!/usr/bin/env python3
# Copyright 2026 ETH Zurich and University of Bologna.
# Licensed under the Apache License, Version 2.0, see LICENSE for details.
# SPDX-License-Identifier: Apache-2.0
#
# Author: Pei-Yu Lin <peilin@ethz.ch>
#
# gen_data.py — generate fp32 VME GEMM data header.
#
# Usage:
#   python3 script/gen_data.py -c script/gemm_64_64_64.json
#
# Output:
#   data/data_{M}_{N}_{K}.h
#
# The config JSON must provide: M, N, K.
# Optional fields: TM (default 16), TN (default 16), seed (default 42).

import argparse
import pathlib

import hjson
import numpy as np
import torch


def array_to_cstr_f32(arr: np.ndarray) -> str:
    """Flat float32 array → C brace-initializer with 'f' suffix."""
    return "{" + ", ".join(repr(float(x)) + "f" for x in arr.flat) + "}"


def main():
    parser = argparse.ArgumentParser(
        description="Generate fp32 VME GEMM benchmark data header"
    )
    parser.add_argument(
        "-c", "--cfg",
        type=pathlib.Path,
        required=True,
        help="JSON/HJSON config file (e.g. script/gemm_64_64_64.json)",
    )
    parser.add_argument("-v", "--verbose", action="store_true")
    args = parser.parse_args()

    with args.cfg.open() as f:
        param = hjson.loads(f.read())

    M    = int(param["M"])
    N    = int(param["N"])
    K    = int(param["K"])
    TM   = int(param.get("TM", 16))
    TN   = int(param.get("TN", 16))
    seed = int(param.get("seed", 42))

    assert M % (2 * TM) == 0, f"M={M} must be a multiple of 2*TM={2*TM}"
    assert N % (2 * TN) == 0, f"N={N} must be a multiple of 2*TN={2*TN}"

    torch.manual_seed(seed)
    np.random.seed(seed)

    A = torch.randn((M, K), dtype=torch.float32).numpy()
    B = torch.randn((K, N), dtype=torch.float32).numpy()
    C = (torch.tensor(A) @ torch.tensor(B)).numpy()

    # Contiguous k-fused-quad packing for the kcontig kernels.
    TK = 4
    TW16 = 16
    assert K % TK == 0
    assert M % TW16 == 0 and N % TW16 == 0
    # A_pack[m_tile, k_group, slice, col] = A[m_tile*TW + col, 4*kg + slice]
    A_pack = (A.reshape(M // TW16, TW16, K // TK, TK)   # (mt, col, kg, slice)
                .transpose(0, 2, 3, 1)              # (mt, kg, slice, col)
                .copy())
    B_pack = (B.reshape(K // TK, TK, N // TW16, TW16)   # (kg, slice, nt, col)
                .transpose(2, 0, 1, 3)              # (nt, kg, slice, col)
                .copy())
    if args.verbose:
        print(f"A {A.shape}  min={A.min():.4f}  max={A.max():.4f}")
        print(f"B {B.shape}  min={B.min():.4f}  max={B.max():.4f}")
        print(f"C {C.shape}  min={C.min():.4f}  max={C.max():.4f}")

    lines = [
        "// Copyright 2026 ETH Zurich and University of Bologna.",
        "// Licensed under the Apache License, Version 2.0, see LICENSE for details.",
        "// SPDX-License-Identifier: Apache-2.0",
        "//",
        "// Author: Pei-Yu Lin <peilin@ethz.ch>",
        "//",
        "// Auto-generated by script/gen_data.py — do not edit by hand.",
        "",
        '#include "layer.h"',
        "",
        "const vme_matmul_layer matmul_l = {",
        f"    .M  = {M},",
        f"    .N  = {N},",
        f"    .K  = {K},",
        "};",
        "",
        "// C[M*N] row-major fp32 golden reference, C = A*B",
        f'static float Cref_dram[{M}*{N}] __attribute__((section(".data"))) =',
        array_to_cstr_f32(C) + ";",
        "",
        "",
        "// Contiguous k-fused-quad packing (for the kcontig / LMUL=4 kernel).",
        "// A_pack[m_tile][k_group][slice][col], slice-major so a whole tk=4 quad",
        "// (64 fp32) is contiguous -> one LMUL=4 vle32.v loads it into 4 vregs.",
        "// quad ptr for (m_tile mt, k_group g) = Apack_dram + (mt*(K/4)+g)*64.",
        f'static float Apack_dram[{K}*{M}] __attribute__((section(".data"))) =',
        array_to_cstr_f32(A_pack) + ";",
        "",
        "",
        "// B_pack[n_tile][k_group][slice][col]; quad ptr for (n_tile nt, k_group g)",
        "// = Bpack_dram + (nt*(K/4)+g)*64.",
        f'static float Bpack_dram[{K}*{N}] __attribute__((section(".data"))) =',
        array_to_cstr_f32(B_pack) + ";",
        "",
    ]

    out_dir = pathlib.Path(__file__).parent.parent / "data"
    out_dir.mkdir(parents=True, exist_ok=True)
    out_file = out_dir / f"data_{M}_{N}_{K}.h"

    with out_file.open("w") as f:
        f.write("\n".join(lines))

    print(f"Written: {out_file}")


if __name__ == "__main__":
    main()
