// Copyright 2020 ETH Zurich and University of Bologna.
// Licensed under the Apache License, Version 2.0, see LICENSE for details.
// SPDX-License-Identifier: Apache-2.0

// Generated by occamygen.py

#pragma once

#define UART_BASE_ADDR 0x03002000
#define QUADRANT_0_CLUSTER_0_TCDM_BASE_ADDR 0x51000000
#define QUADRANT_0_CLUSTER_0_PERIPH_BASE_ADDR 0x51010000
