#!/usr/bin/env python3
# Copyright 2026 ETH Zurich and University of Bologna.
# Licensed under the Apache License, Version 2.0, see LICENSE for details.
# SPDX-License-Identifier: Apache-2.0
#
# Author: Pei-Yu Lin <peilin@ethz.ch>
#
# gen_data.py — generate fp32 VME GEMM data header.
#
# Usage:
#   python3 script/gen_data.py -c script/gemm_64_64_64.json
#
# Output:
#   data/data_{M}_{N}_{K}.h
#
# The config JSON must provide: M, N, K.
# Optional fields: TM (default 16), TN (default 16), seed (default 42).

import argparse
import pathlib

import hjson
import numpy as np
import torch


def array_to_cstr_f32(arr: np.ndarray) -> str:
    """Flat float32 array → C brace-initializer with 'f' suffix."""
    return "{" + ", ".join(repr(float(x)) + "f" for x in arr.flat) + "}"


def main():
    parser = argparse.ArgumentParser(
        description="Generate fp32 VME GEMM benchmark data header"
    )
    parser.add_argument(
        "-c", "--cfg",
        type=pathlib.Path,
        required=True,
        help="JSON/HJSON config file (e.g. script/gemm_64_64_64.json)",
    )
    parser.add_argument("-v", "--verbose", action="store_true")
    args = parser.parse_args()

    with args.cfg.open() as f:
        param = hjson.loads(f.read())

    M    = int(param["M"])
    N    = int(param["N"])
    K    = int(param["K"])
    TM   = int(param.get("TM", 16))
    TN   = int(param.get("TN", 16))
    seed = int(param.get("seed", 42))

    assert M % (2 * TM) == 0, f"M={M} must be a multiple of 2*TM={2*TM}"
    assert N % (2 * TN) == 0, f"N={N} must be a multiple of 2*TN={2*TN}"

    torch.manual_seed(seed)
    np.random.seed(seed)

    A = torch.randn((M, K), dtype=torch.float32).numpy()
    B = torch.randn((K, N), dtype=torch.float32).numpy()
    C = (torch.tensor(A) @ torch.tensor(B)).numpy()
    checksum = C.sum(axis=1)

    if args.verbose:
        print(f"A {A.shape}  min={A.min():.4f}  max={A.max():.4f}")
        print(f"B {B.shape}  min={B.min():.4f}  max={B.max():.4f}")
        print(f"C {C.shape}  min={C.min():.4f}  max={C.max():.4f}")

    lines = [
        "// Copyright 2026 ETH Zurich and University of Bologna.",
        "// Licensed under the Apache License, Version 2.0, see LICENSE for details.",
        "// SPDX-License-Identifier: Apache-2.0",
        "//",
        "// Author: Pei-Yu Lin <peilin@ethz.ch>",
        "//",
        "// Auto-generated by script/gen_data.py — do not edit by hand.",
        "",
        '#include "layer.h"',
        "",
        "const vme_gemm_layer gemm_l = {",
        f"    .M  = {M},",
        f"    .N  = {N},",
        f"    .K  = {K},",
        f"    .TM = {TM},",
        f"    .TN = {TN},",
        "};",
        "",
        "// A[M*K] row-major fp32, A[i][k] = A[i*K+k]",
        f'static float gemm_A_dram[{M}*{K}] __attribute__((section(".data"))) =',
        array_to_cstr_f32(A) + ";",
        "",
        "",
        "// B[K*N] row-major fp32, B[k][j] = B[k*N+j]",
        f'static float gemm_B_dram[{K}*{N}] __attribute__((section(".data"))) =',
        array_to_cstr_f32(B) + ";",
        "",
        "",
        "// Row sums of fp32 reference C = A*B (one entry per row of C).",
        f"static const float gemm_checksum[{M}] =",
        array_to_cstr_f32(checksum) + ";",
        "",
    ]

    out_dir = pathlib.Path(__file__).parent.parent / "data"
    out_dir.mkdir(parents=True, exist_ok=True)
    out_file = out_dir / f"data_{M}_{N}_{K}.h"

    with out_file.open("w") as f:
        f.write("\n".join(lines))

    print(f"Written: {out_file}")


if __name__ == "__main__":
    main()
