#!/usr/bin/env python3
# Copyright 2026 ETH Zurich and University of Bologna.
# Licensed under the Apache License, Version 2.0, see LICENSE for details.
# SPDX-License-Identifier: Apache-2.0
#
# Author: Pei-Yu Lin, ETH Zürich
#
#
# Usage:
#   python3 script/gen_data.py -c script/matmul_64_64_64.json
#
# Output:
#   data/data_{M}_{N}_{K}.h
#
# The config JSON must provide: M, N, K.
# Required fields: TM, TN; optional field: seed (default 42).

import argparse
import pathlib

import hjson
import numpy as np
import torch

def array_to_cstr_f32(arr: np.ndarray) -> str:
    """Flat float32 array → C brace-initializer with 'f' suffix."""
    return "{" + ", ".join(repr(float(x)) + "f" for x in arr.flat) + "}"

def main():
    parser = argparse.ArgumentParser(
        description="Generate fp32 VME GEMM benchmark data header"
    )
    parser.add_argument(
        "-c", "--cfg",
        type=pathlib.Path,
        required=True,
        help="JSON/HJSON config file (e.g. script/matmul_64_64_64.json)",
    )
    args = parser.parse_args()

    with args.cfg.open() as f:
        param = hjson.loads(f.read())

    M    = int(param["M"])
    N    = int(param["N"])
    K    = int(param["K"])
    TM   = int(param["TM"])
    TN   = int(param["TN"])
    seed = int(param.get("seed", 42))

    assert M % (2 * TM) == 0, f"M={M} must be a multiple of 2*TM={2*TM}"
    assert N % (2 * TN) == 0, f"N={N} must be a multiple of 2*TN={2*TN}"

    torch.manual_seed(seed)

    A = torch.randn((M, K), dtype=torch.float32).numpy()
    B = torch.randn((K, N), dtype=torch.float32).numpy()
    C = (torch.from_numpy(A) @ torch.from_numpy(B)).numpy()

    # Pack one complete TE32 vector for every K value in each matrix tile.
    A_pack = A.reshape(M // TM, TM, K).transpose(0, 2, 1).copy()
    B_pack = B.reshape(K, N // TN, TN).transpose(1, 0, 2).copy()

    lines = [
        "// Copyright 2026 ETH Zurich and University of Bologna.",
        "// Licensed under the Apache License, Version 2.0, see LICENSE for details.",
        "// SPDX-License-Identifier: Apache-2.0",
        "//",
        "// Author: Pei-Yu Lin, ETH Zürich",
        "//",
        "// Auto-generated by script/gen_data.py — do not edit by hand.",
        "",
        '#include "layer.h"',
        "",
        "const matmul_layer matmul_l = {",
        f"    .M  = {M},",
        f"    .N  = {N},",
        f"    .K  = {K},",
        "};",
        "",
        "// C[M*N] row-major fp32 golden reference, C = A*B",
        f'static float Cref_dram[{M}*{N}] __attribute__((section(".data"))) =',
        array_to_cstr_f32(C) + ";",
        "",
        "",
        "// A_pack[m_tile][k][row] stores one TE32 row vector per K value.",
        f'static float Apack_dram[{K}*{M}] __attribute__((section(".data"))) =',
        array_to_cstr_f32(A_pack) + ";",
        "",
        "",
        "// B_pack[n_tile][k][col] stores one TE32 column vector per K value.",
        f'static float Bpack_dram[{K}*{N}] __attribute__((section(".data"))) =',
        array_to_cstr_f32(B_pack) + ";",
        "",
    ]

    out_dir = pathlib.Path(__file__).parent.parent / "data"
    out_dir.mkdir(parents=True, exist_ok=True)
    out_file = out_dir / f"data_{M}_{N}_{K}.h"

    with out_file.open("w") as f:
        f.write("\n".join(lines))

    print(f"Written: {out_file}")

if __name__ == "__main__":
    main()
