#!/usr/bin/env python3
# Copyright 2026 ETH Zurich and University of Bologna.
# Licensed under the Apache License, Version 2.0, see LICENSE for details.
# SPDX-License-Identifier: Apache-2.0
#
# Author: Pei-Yu Lin <peilin@ethz.ch>
#
#
# Usage:
#   python3 script/gen_data.py -c script/matmul_128_128_128.json
#
# Output:
#   data/data_{M}_{N}_{K}.h
#
# The config JSON must provide: M, N, K.
# Optional field: seed (default 42).

import argparse
import pathlib

import hjson
import numpy as np
import torch

def array_to_cstr_f32(arr: np.ndarray) -> str:
    """Flat float32 array → C brace-initializer with 'f' suffix."""
    return "{" + ", ".join(repr(float(x)) + "f" for x in arr.flat) + "}"

def array_to_cstr_u32(arr: np.ndarray) -> str:
    return "{" + ", ".join(f"0x{int(x):08x}u" for x in arr.flat) + "}"

def pack_pairs(a: np.ndarray, b: np.ndarray, te: int = 32):
    """Words are {even K halfword, odd K halfword}; no FP32 conversion."""
    m, k = a.shape
    assert b.shape[0] == k and k % 2 == 0
    n = b.shape[1]
    assert m % te == 0 and n % te == 0
    abits = a.astype(np.float16).view(np.uint16).astype(np.uint32)
    bbits = b.astype(np.float16).view(np.uint16).astype(np.uint32)
    aw = (abits[:, 0::2] << 16) | abits[:, 1::2]
    bw = (bbits[0::2, :] << 16) | bbits[1::2, :]
    return (aw.reshape(m // te, te, k // 2).transpose(0, 2, 1).copy(),
            bw.reshape(k // 2, n // te, te).transpose(1, 0, 2).copy())

def main():
    parser = argparse.ArgumentParser(
        description="Generate FP16xFP16->FP32 VME GEMM benchmark data header"
    )
    parser.add_argument(
        "-c", "--cfg",
        type=pathlib.Path,
        required=True,
        help="JSON/HJSON config file (e.g. script/matmul_128_128_128.json)",
    )
    args = parser.parse_args()

    with args.cfg.open() as f:
        param = hjson.loads(f.read())

    M    = int(param["M"])
    N    = int(param["N"])
    K    = int(param["K"])
    seed = int(param.get("seed", 42))
    if K < 24 or K % 8:
        parser.error("store-afterK requires real K >= 24 and divisible by 8")

    torch.manual_seed(seed)

    A = torch.randn((M, K), dtype=torch.float32).to(torch.float16)
    B = torch.randn((K, N), dtype=torch.float32).to(torch.float16)
    C = (A.to(torch.float32) @ B.to(torch.float32)).numpy()
    A = A.numpy()
    B = B.numpy()

    A_pack, B_pack = pack_pairs(A, B)

    lines = [
        "// Copyright 2026 ETH Zurich and University of Bologna.",
        "// Licensed under the Apache License, Version 2.0, see LICENSE for details.",
        "// SPDX-License-Identifier: Apache-2.0",
        "//",
        "// Author: Pei-Yu Lin <peilin@ethz.ch>",
        "//",
        "// Auto-generated by script/gen_data.py — do not edit by hand.",
        "",
        '#include "layer.h"',
        '#include <stdint.h>',
        "",
        "const matmul_layer matmul_l = {",
        f"    .M  = {M},",
        f"    .N  = {N},",
        f"    .K  = {K},",
        "};",
        "",
        "// C[M*N] row-major fp32 golden reference, C = A*B",
        f'static float Cref_dram[{M}*{N}] __attribute__((section(".data"))) =',
        array_to_cstr_f32(C) + ";",
        "",
        "",
        "// A_pack[m_tile][K/2][32]: word[31:16]=even K, word[15:0]=odd K.",
        "// vle32 with VL=16 transfers one 512-bit packed K pair.",
        f'static uint32_t Apack_dram[{K//2}*{M}] __attribute__((section(".data"), aligned(64))) =',
        array_to_cstr_u32(A_pack) + ";",
        "",
        "",
        "// B_pack[n_tile][K/2][32], same halfword order as A.",
        f'static uint32_t Bpack_dram[{K//2}*{N}] __attribute__((section(".data"), aligned(64))) =',
        array_to_cstr_u32(B_pack) + ";",
        "",
    ]

    out_dir = pathlib.Path(__file__).parent.parent / "data"
    out_dir.mkdir(parents=True, exist_ok=True)
    out_file = out_dir / f"data_{M}_{N}_{K}.h"

    with out_file.open("w") as f:
        f.write("\n".join(lines))

    print(f"Written: {out_file}")

if __name__ == "__main__":
    main()
