// Copyright lowRISC contributors.
// Licensed under the Apache License, Version 2.0, see LICENSE for details.
// SPDX-License-Identifier: Apache-2.0
//
// Register Top module auto-generated by `reggen`


`include "common_cells/assertions.svh"

module hmr_dmr_regs_reg_top #(
  parameter type reg_req_t = logic,
  parameter type reg_rsp_t = logic,
  parameter int AW = 4
) (
  input logic clk_i,
  input logic rst_ni,
  input  reg_req_t reg_req_i,
  output reg_rsp_t reg_rsp_o,
  // To HW
  output hmr_dmr_regs_reg_pkg::hmr_dmr_regs_reg2hw_t reg2hw, // Write
  input  hmr_dmr_regs_reg_pkg::hmr_dmr_regs_hw2reg_t hw2reg, // Read


  // Config
  input devmode_i // If 1, explicit error return for unmapped register access
);

  import hmr_dmr_regs_reg_pkg::* ;

  localparam int DW = 32;
  localparam int DBW = DW/8;                    // Byte Width

  // register signals
  logic           reg_we;
  logic           reg_re;
  logic [AW-1:0]  reg_addr;
  logic [DW-1:0]  reg_wdata;
  logic [DBW-1:0] reg_be;
  logic [DW-1:0]  reg_rdata;
  logic           reg_error;

  logic          addrmiss, wr_err;

  logic [DW-1:0] reg_rdata_next;

  // Below register interface can be changed
  reg_req_t  reg_intf_req;
  reg_rsp_t  reg_intf_rsp;


  assign reg_intf_req = reg_req_i;
  assign reg_rsp_o = reg_intf_rsp;


  assign reg_we = reg_intf_req.valid & reg_intf_req.write;
  assign reg_re = reg_intf_req.valid & ~reg_intf_req.write;
  assign reg_addr = reg_intf_req.addr;
  assign reg_wdata = reg_intf_req.wdata;
  assign reg_be = reg_intf_req.wstrb;
  assign reg_intf_rsp.rdata = reg_rdata;
  assign reg_intf_rsp.error = reg_error;
  assign reg_intf_rsp.ready = 1'b1;

  assign reg_rdata = reg_rdata_next ;
  assign reg_error = (devmode_i & addrmiss) | wr_err;


  // Define SW related signals
  // Format: <reg>_<field>_{wd|we|qs}
  //        or <reg>_{wd|we|qs} if field == 1 or 0
  logic dmr_enable_qs;
  logic dmr_enable_wd;
  logic dmr_enable_we;
  logic dmr_config_rapid_recovery_qs;
  logic dmr_config_rapid_recovery_wd;
  logic dmr_config_rapid_recovery_we;
  logic dmr_config_force_recovery_qs;
  logic dmr_config_force_recovery_wd;
  logic dmr_config_force_recovery_we;
  logic [31:0] checkpoint_addr_qs;
  logic [31:0] checkpoint_addr_wd;
  logic checkpoint_addr_we;

  // Register instances
  // R[dmr_enable]: V(False)

  prim_subreg #(
    .DW      (1),
    .SWACCESS("RW"),
    .RESVAL  (1'h0)
  ) u_dmr_enable (
    .clk_i   (clk_i    ),
    .rst_ni  (rst_ni  ),

    // from register interface
    .we     (dmr_enable_we),
    .wd     (dmr_enable_wd),

    // from internal hardware
    .de     (hw2reg.dmr_enable.de),
    .d      (hw2reg.dmr_enable.d ),

    // to internal hardware
    .qe     (reg2hw.dmr_enable.qe),
    .q      (reg2hw.dmr_enable.q ),

    // to register interface (read)
    .qs     (dmr_enable_qs)
  );


  // R[dmr_config]: V(False)

  //   F[rapid_recovery]: 0:0
  prim_subreg #(
    .DW      (1),
    .SWACCESS("RW"),
    .RESVAL  (1'h0)
  ) u_dmr_config_rapid_recovery (
    .clk_i   (clk_i    ),
    .rst_ni  (rst_ni  ),

    // from register interface
    .we     (dmr_config_rapid_recovery_we),
    .wd     (dmr_config_rapid_recovery_wd),

    // from internal hardware
    .de     (hw2reg.dmr_config.rapid_recovery.de),
    .d      (hw2reg.dmr_config.rapid_recovery.d ),

    // to internal hardware
    .qe     (reg2hw.dmr_config.rapid_recovery.qe),
    .q      (reg2hw.dmr_config.rapid_recovery.q ),

    // to register interface (read)
    .qs     (dmr_config_rapid_recovery_qs)
  );


  //   F[force_recovery]: 1:1
  prim_subreg #(
    .DW      (1),
    .SWACCESS("RW"),
    .RESVAL  (1'h0)
  ) u_dmr_config_force_recovery (
    .clk_i   (clk_i    ),
    .rst_ni  (rst_ni  ),

    // from register interface
    .we     (dmr_config_force_recovery_we),
    .wd     (dmr_config_force_recovery_wd),

    // from internal hardware
    .de     (hw2reg.dmr_config.force_recovery.de),
    .d      (hw2reg.dmr_config.force_recovery.d ),

    // to internal hardware
    .qe     (reg2hw.dmr_config.force_recovery.qe),
    .q      (reg2hw.dmr_config.force_recovery.q ),

    // to register interface (read)
    .qs     (dmr_config_force_recovery_qs)
  );


  // R[checkpoint_addr]: V(False)

  prim_subreg #(
    .DW      (32),
    .SWACCESS("RW"),
    .RESVAL  (32'h0)
  ) u_checkpoint_addr (
    .clk_i   (clk_i    ),
    .rst_ni  (rst_ni  ),

    // from register interface
    .we     (checkpoint_addr_we),
    .wd     (checkpoint_addr_wd),

    // from internal hardware
    .de     (hw2reg.checkpoint_addr.de),
    .d      (hw2reg.checkpoint_addr.d ),

    // to internal hardware
    .qe     (reg2hw.checkpoint_addr.qe),
    .q      (reg2hw.checkpoint_addr.q ),

    // to register interface (read)
    .qs     (checkpoint_addr_qs)
  );




  logic [2:0] addr_hit;
  always_comb begin
    addr_hit = '0;
    addr_hit[0] = (reg_addr == HMR_DMR_REGS_DMR_ENABLE_OFFSET);
    addr_hit[1] = (reg_addr == HMR_DMR_REGS_DMR_CONFIG_OFFSET);
    addr_hit[2] = (reg_addr == HMR_DMR_REGS_CHECKPOINT_ADDR_OFFSET);
  end

  assign addrmiss = (reg_re || reg_we) ? ~|addr_hit : 1'b0 ;

  // Check sub-word write is permitted
  always_comb begin
    wr_err = (reg_we &
              ((addr_hit[0] & (|(HMR_DMR_REGS_PERMIT[0] & ~reg_be))) |
               (addr_hit[1] & (|(HMR_DMR_REGS_PERMIT[1] & ~reg_be))) |
               (addr_hit[2] & (|(HMR_DMR_REGS_PERMIT[2] & ~reg_be)))));
  end

  assign dmr_enable_we = addr_hit[0] & reg_we & !reg_error;
  assign dmr_enable_wd = reg_wdata[0];

  assign dmr_config_rapid_recovery_we = addr_hit[1] & reg_we & !reg_error;
  assign dmr_config_rapid_recovery_wd = reg_wdata[0];

  assign dmr_config_force_recovery_we = addr_hit[1] & reg_we & !reg_error;
  assign dmr_config_force_recovery_wd = reg_wdata[1];

  assign checkpoint_addr_we = addr_hit[2] & reg_we & !reg_error;
  assign checkpoint_addr_wd = reg_wdata[31:0];

  // Read data return
  always_comb begin
    reg_rdata_next = '0;
    unique case (1'b1)
      addr_hit[0]: begin
        reg_rdata_next[0] = dmr_enable_qs;
      end

      addr_hit[1]: begin
        reg_rdata_next[0] = dmr_config_rapid_recovery_qs;
        reg_rdata_next[1] = dmr_config_force_recovery_qs;
      end

      addr_hit[2]: begin
        reg_rdata_next[31:0] = checkpoint_addr_qs;
      end

      default: begin
        reg_rdata_next = '1;
      end
    endcase
  end

  // Unused signal tieoff

  // wdata / byte enable are not always fully used
  // add a blanket unused statement to handle lint waivers
  logic unused_wdata;
  logic unused_be;
  assign unused_wdata = ^reg_wdata;
  assign unused_be = ^reg_be;

  // Assertions for Register Interface
  `ASSERT(en2addrHit, (reg_we || reg_re) |-> $onehot0(addr_hit))

endmodule

module hmr_dmr_regs_reg_top_intf
#(
  parameter int AW = 4,
  localparam int DW = 32
) (
  input logic clk_i,
  input logic rst_ni,
  REG_BUS.in  regbus_slave,
  // To HW
  output hmr_dmr_regs_reg_pkg::hmr_dmr_regs_reg2hw_t reg2hw, // Write
  input  hmr_dmr_regs_reg_pkg::hmr_dmr_regs_hw2reg_t hw2reg, // Read
  // Config
  input devmode_i // If 1, explicit error return for unmapped register access
);
 localparam int unsigned STRB_WIDTH = DW/8;

`include "register_interface/typedef.svh"
`include "register_interface/assign.svh"

  // Define structs for reg_bus
  typedef logic [AW-1:0] addr_t;
  typedef logic [DW-1:0] data_t;
  typedef logic [STRB_WIDTH-1:0] strb_t;
  `REG_BUS_TYPEDEF_ALL(reg_bus, addr_t, data_t, strb_t)

  reg_bus_req_t s_reg_req;
  reg_bus_rsp_t s_reg_rsp;
  
  // Assign SV interface to structs
  `REG_BUS_ASSIGN_TO_REQ(s_reg_req, regbus_slave)
  `REG_BUS_ASSIGN_FROM_RSP(regbus_slave, s_reg_rsp)

  

  hmr_dmr_regs_reg_top #(
    .reg_req_t(reg_bus_req_t),
    .reg_rsp_t(reg_bus_rsp_t),
    .AW(AW)
  ) i_regs (
    .clk_i,
    .rst_ni,
    .reg_req_i(s_reg_req),
    .reg_rsp_o(s_reg_rsp),
    .reg2hw, // Write
    .hw2reg, // Read
    .devmode_i
  );
  
endmodule


