// Copyright lowRISC contributors.
// Licensed under the Apache License, Version 2.0, see LICENSE for details.
// SPDX-License-Identifier: Apache-2.0
//
// Register Top module auto-generated by `reggen`


`include "common_cells/assertions.svh"

module hmr_tmr_regs_reg_top #(
  parameter type reg_req_t = logic,
  parameter type reg_rsp_t = logic,
  parameter int AW = 3
) (
  input logic clk_i,
  input logic rst_ni,
  input  reg_req_t reg_req_i,
  output reg_rsp_t reg_rsp_o,
  // To HW
  output hmr_tmr_regs_reg_pkg::hmr_tmr_regs_reg2hw_t reg2hw, // Write
  input  hmr_tmr_regs_reg_pkg::hmr_tmr_regs_hw2reg_t hw2reg, // Read


  // Config
  input devmode_i // If 1, explicit error return for unmapped register access
);

  import hmr_tmr_regs_reg_pkg::* ;

  localparam int DW = 32;
  localparam int DBW = DW/8;                    // Byte Width

  // register signals
  logic           reg_we;
  logic           reg_re;
  logic [AW-1:0]  reg_addr;
  logic [DW-1:0]  reg_wdata;
  logic [DBW-1:0] reg_be;
  logic [DW-1:0]  reg_rdata;
  logic           reg_error;

  logic          addrmiss, wr_err;

  logic [DW-1:0] reg_rdata_next;

  // Below register interface can be changed
  reg_req_t  reg_intf_req;
  reg_rsp_t  reg_intf_rsp;


  assign reg_intf_req = reg_req_i;
  assign reg_rsp_o = reg_intf_rsp;


  assign reg_we = reg_intf_req.valid & reg_intf_req.write;
  assign reg_re = reg_intf_req.valid & ~reg_intf_req.write;
  assign reg_addr = reg_intf_req.addr;
  assign reg_wdata = reg_intf_req.wdata;
  assign reg_be = reg_intf_req.wstrb;
  assign reg_intf_rsp.rdata = reg_rdata;
  assign reg_intf_rsp.error = reg_error;
  assign reg_intf_rsp.ready = 1'b1;

  assign reg_rdata = reg_rdata_next ;
  assign reg_error = (devmode_i & addrmiss) | wr_err;


  // Define SW related signals
  // Format: <reg>_<field>_{wd|we|qs}
  //        or <reg>_{wd|we|qs} if field == 1 or 0
  logic tmr_enable_qs;
  logic tmr_enable_wd;
  logic tmr_enable_we;
  logic tmr_config_delay_resynch_qs;
  logic tmr_config_delay_resynch_wd;
  logic tmr_config_delay_resynch_we;
  logic tmr_config_setback_qs;
  logic tmr_config_setback_wd;
  logic tmr_config_setback_we;
  logic tmr_config_reload_setback_qs;
  logic tmr_config_reload_setback_wd;
  logic tmr_config_reload_setback_we;
  logic tmr_config_rapid_recovery_qs;
  logic tmr_config_rapid_recovery_wd;
  logic tmr_config_rapid_recovery_we;
  logic tmr_config_force_resynch_qs;
  logic tmr_config_force_resynch_wd;
  logic tmr_config_force_resynch_we;

  // Register instances
  // R[tmr_enable]: V(False)

  prim_subreg #(
    .DW      (1),
    .SWACCESS("RW"),
    .RESVAL  (1'h0)
  ) u_tmr_enable (
    .clk_i   (clk_i    ),
    .rst_ni  (rst_ni  ),

    // from register interface
    .we     (tmr_enable_we),
    .wd     (tmr_enable_wd),

    // from internal hardware
    .de     (hw2reg.tmr_enable.de),
    .d      (hw2reg.tmr_enable.d ),

    // to internal hardware
    .qe     (reg2hw.tmr_enable.qe),
    .q      (reg2hw.tmr_enable.q ),

    // to register interface (read)
    .qs     (tmr_enable_qs)
  );


  // R[tmr_config]: V(False)

  //   F[delay_resynch]: 0:0
  prim_subreg #(
    .DW      (1),
    .SWACCESS("RW"),
    .RESVAL  (1'h0)
  ) u_tmr_config_delay_resynch (
    .clk_i   (clk_i    ),
    .rst_ni  (rst_ni  ),

    // from register interface
    .we     (tmr_config_delay_resynch_we),
    .wd     (tmr_config_delay_resynch_wd),

    // from internal hardware
    .de     (hw2reg.tmr_config.delay_resynch.de),
    .d      (hw2reg.tmr_config.delay_resynch.d ),

    // to internal hardware
    .qe     (reg2hw.tmr_config.delay_resynch.qe),
    .q      (reg2hw.tmr_config.delay_resynch.q ),

    // to register interface (read)
    .qs     (tmr_config_delay_resynch_qs)
  );


  //   F[setback]: 1:1
  prim_subreg #(
    .DW      (1),
    .SWACCESS("RW"),
    .RESVAL  (1'h1)
  ) u_tmr_config_setback (
    .clk_i   (clk_i    ),
    .rst_ni  (rst_ni  ),

    // from register interface
    .we     (tmr_config_setback_we),
    .wd     (tmr_config_setback_wd),

    // from internal hardware
    .de     (hw2reg.tmr_config.setback.de),
    .d      (hw2reg.tmr_config.setback.d ),

    // to internal hardware
    .qe     (reg2hw.tmr_config.setback.qe),
    .q      (reg2hw.tmr_config.setback.q ),

    // to register interface (read)
    .qs     (tmr_config_setback_qs)
  );


  //   F[reload_setback]: 2:2
  prim_subreg #(
    .DW      (1),
    .SWACCESS("RW"),
    .RESVAL  (1'h1)
  ) u_tmr_config_reload_setback (
    .clk_i   (clk_i    ),
    .rst_ni  (rst_ni  ),

    // from register interface
    .we     (tmr_config_reload_setback_we),
    .wd     (tmr_config_reload_setback_wd),

    // from internal hardware
    .de     (hw2reg.tmr_config.reload_setback.de),
    .d      (hw2reg.tmr_config.reload_setback.d ),

    // to internal hardware
    .qe     (reg2hw.tmr_config.reload_setback.qe),
    .q      (reg2hw.tmr_config.reload_setback.q ),

    // to register interface (read)
    .qs     (tmr_config_reload_setback_qs)
  );


  //   F[rapid_recovery]: 3:3
  prim_subreg #(
    .DW      (1),
    .SWACCESS("RW"),
    .RESVAL  (1'h0)
  ) u_tmr_config_rapid_recovery (
    .clk_i   (clk_i    ),
    .rst_ni  (rst_ni  ),

    // from register interface
    .we     (tmr_config_rapid_recovery_we),
    .wd     (tmr_config_rapid_recovery_wd),

    // from internal hardware
    .de     (hw2reg.tmr_config.rapid_recovery.de),
    .d      (hw2reg.tmr_config.rapid_recovery.d ),

    // to internal hardware
    .qe     (reg2hw.tmr_config.rapid_recovery.qe),
    .q      (reg2hw.tmr_config.rapid_recovery.q ),

    // to register interface (read)
    .qs     (tmr_config_rapid_recovery_qs)
  );


  //   F[force_resynch]: 4:4
  prim_subreg #(
    .DW      (1),
    .SWACCESS("RW"),
    .RESVAL  (1'h0)
  ) u_tmr_config_force_resynch (
    .clk_i   (clk_i    ),
    .rst_ni  (rst_ni  ),

    // from register interface
    .we     (tmr_config_force_resynch_we),
    .wd     (tmr_config_force_resynch_wd),

    // from internal hardware
    .de     (hw2reg.tmr_config.force_resynch.de),
    .d      (hw2reg.tmr_config.force_resynch.d ),

    // to internal hardware
    .qe     (reg2hw.tmr_config.force_resynch.qe),
    .q      (reg2hw.tmr_config.force_resynch.q ),

    // to register interface (read)
    .qs     (tmr_config_force_resynch_qs)
  );




  logic [1:0] addr_hit;
  always_comb begin
    addr_hit = '0;
    addr_hit[0] = (reg_addr == HMR_TMR_REGS_TMR_ENABLE_OFFSET);
    addr_hit[1] = (reg_addr == HMR_TMR_REGS_TMR_CONFIG_OFFSET);
  end

  assign addrmiss = (reg_re || reg_we) ? ~|addr_hit : 1'b0 ;

  // Check sub-word write is permitted
  always_comb begin
    wr_err = (reg_we &
              ((addr_hit[0] & (|(HMR_TMR_REGS_PERMIT[0] & ~reg_be))) |
               (addr_hit[1] & (|(HMR_TMR_REGS_PERMIT[1] & ~reg_be)))));
  end

  assign tmr_enable_we = addr_hit[0] & reg_we & !reg_error;
  assign tmr_enable_wd = reg_wdata[0];

  assign tmr_config_delay_resynch_we = addr_hit[1] & reg_we & !reg_error;
  assign tmr_config_delay_resynch_wd = reg_wdata[0];

  assign tmr_config_setback_we = addr_hit[1] & reg_we & !reg_error;
  assign tmr_config_setback_wd = reg_wdata[1];

  assign tmr_config_reload_setback_we = addr_hit[1] & reg_we & !reg_error;
  assign tmr_config_reload_setback_wd = reg_wdata[2];

  assign tmr_config_rapid_recovery_we = addr_hit[1] & reg_we & !reg_error;
  assign tmr_config_rapid_recovery_wd = reg_wdata[3];

  assign tmr_config_force_resynch_we = addr_hit[1] & reg_we & !reg_error;
  assign tmr_config_force_resynch_wd = reg_wdata[4];

  // Read data return
  always_comb begin
    reg_rdata_next = '0;
    unique case (1'b1)
      addr_hit[0]: begin
        reg_rdata_next[0] = tmr_enable_qs;
      end

      addr_hit[1]: begin
        reg_rdata_next[0] = tmr_config_delay_resynch_qs;
        reg_rdata_next[1] = tmr_config_setback_qs;
        reg_rdata_next[2] = tmr_config_reload_setback_qs;
        reg_rdata_next[3] = tmr_config_rapid_recovery_qs;
        reg_rdata_next[4] = tmr_config_force_resynch_qs;
      end

      default: begin
        reg_rdata_next = '1;
      end
    endcase
  end

  // Unused signal tieoff

  // wdata / byte enable are not always fully used
  // add a blanket unused statement to handle lint waivers
  logic unused_wdata;
  logic unused_be;
  assign unused_wdata = ^reg_wdata;
  assign unused_be = ^reg_be;

  // Assertions for Register Interface
  `ASSERT(en2addrHit, (reg_we || reg_re) |-> $onehot0(addr_hit))

endmodule

module hmr_tmr_regs_reg_top_intf
#(
  parameter int AW = 3,
  localparam int DW = 32
) (
  input logic clk_i,
  input logic rst_ni,
  REG_BUS.in  regbus_slave,
  // To HW
  output hmr_tmr_regs_reg_pkg::hmr_tmr_regs_reg2hw_t reg2hw, // Write
  input  hmr_tmr_regs_reg_pkg::hmr_tmr_regs_hw2reg_t hw2reg, // Read
  // Config
  input devmode_i // If 1, explicit error return for unmapped register access
);
 localparam int unsigned STRB_WIDTH = DW/8;

`include "register_interface/typedef.svh"
`include "register_interface/assign.svh"

  // Define structs for reg_bus
  typedef logic [AW-1:0] addr_t;
  typedef logic [DW-1:0] data_t;
  typedef logic [STRB_WIDTH-1:0] strb_t;
  `REG_BUS_TYPEDEF_ALL(reg_bus, addr_t, data_t, strb_t)

  reg_bus_req_t s_reg_req;
  reg_bus_rsp_t s_reg_rsp;
  
  // Assign SV interface to structs
  `REG_BUS_ASSIGN_TO_REQ(s_reg_req, regbus_slave)
  `REG_BUS_ASSIGN_FROM_RSP(regbus_slave, s_reg_rsp)

  

  hmr_tmr_regs_reg_top #(
    .reg_req_t(reg_bus_req_t),
    .reg_rsp_t(reg_bus_rsp_t),
    .AW(AW)
  ) i_regs (
    .clk_i,
    .rst_ni,
    .reg_req_i(s_reg_req),
    .reg_rsp_o(s_reg_rsp),
    .reg2hw, // Write
    .hw2reg, // Read
    .devmode_i
  );
  
endmodule


