# Copyright 2021 ETH Zurich and University of Bologna.
# Licensed under the Apache License, Version 2.0, see LICENSE for details.
# SPDX-License-Identifier: Apache-2.0

# Author: Matheus Cavalcante, ETH Zurich

variables:
  GIT_SUBMODULE_STRATEGY: none
  ROOT_DIR: '$CI_PROJECT_DIR'
  APPS: "tests"
  RUST_LOG: 'memora=debug'
  VERILATOR_ROOT: '$CI_PROJECT_DIR/install/verilator/share/verilator'
  VERILATOR_BIN: '$CI_PROJECT_DIR/install/verilator/bin'
  OBJCACHE: ''
  RISCV_WARNINGS: '-Werror'
  CC: 'gcc-11.2.0'
  CXX: 'g++-11.2.0'
  CMAKE: 'cmake'
  CTEST: 'ctest'
  VCS: 'vcs-2022.06'
  PYTHON: 'python3'

workflow:
  rules:
    - if: $CI_MERGE_REQUEST_ID
    - if: $CI_COMMIT_TAG
    - if: $CI_COMMIT_REF_NAME

before_script:
  - export PATH="$VERILATOR_BIN:$HOME/.local/bin:$PATH"
  - export PYTHONPATH="$CI_PROJECT_DIR/install/python-deps:$PYTHONPATH"
  - env

stages:
  - tools
  - test
  - lint

###########
#  Tools  #
###########

tc-gcc:
  stage: tools
  script:
    - |
      if ! $CI_PROJECT_DIR/util/memora_retry.sh lookup tc-riscv-gcc; then
        make sw/toolchain/riscv-gnu-toolchain tc-riscv-gcc
        $CI_PROJECT_DIR/util/memora_retry.sh insert tc-riscv-gcc
      fi

tc-llvm:
  stage: tools
  script:
    - |
      if ! $CI_PROJECT_DIR/util/memora_retry.sh lookup tc-llvm; then
        make sw/toolchain/llvm-project tc-llvm
        $CI_PROJECT_DIR/util/memora_retry.sh insert tc-llvm
      fi

verilator:
  stage: tools
  script:
    - |
      if ! $CI_PROJECT_DIR/util/memora_retry.sh lookup verilator; then
        export VERILATOR_CI="--disable-defenv"
        # Verilator requires a more recent version of python than the default one.
        export PYTHON3=$(which python3)
        make sw/toolchain/verilator verilator
        $CI_PROJECT_DIR/util/memora_retry.sh insert verilator
      fi

python-deps:
  stage: tools
  script:
    - |
      if ! $CI_PROJECT_DIR/util/memora_retry.sh lookup python-deps; then
        PIP_USER=0 python3 -m pip install --target=$CI_PROJECT_DIR/install/python-deps -r $CI_PROJECT_DIR/requirements.txt
        PIP_USER=0 python3 -m pip install --target=$CI_PROJECT_DIR/install/python-deps torch --index-url https://download.pytorch.org/whl/cpu
        $CI_PROJECT_DIR/util/memora_retry.sh insert python-deps
      fi

##########
#  Lint  #
##########

# Code style test
code-style:
  stage: lint
  script:
    # Download LLVM and Python deps
    - $CI_PROJECT_DIR/util/memora_retry.sh get tc-llvm
    - $CI_PROJECT_DIR/util/memora_retry.sh get python-deps
    - ./util/lint.sh
  needs: ["tc-llvm", "python-deps"]

###########
#  Build  #
###########

# Runtime tests
snRuntime-test-vsim:
  stage: test
  script:
    # Download LLVM, GCC, and Python deps
    - $CI_PROJECT_DIR/util/memora_retry.sh get tc-llvm
    - $CI_PROJECT_DIR/util/memora_retry.sh get tc-riscv-gcc
    - $CI_PROJECT_DIR/util/memora_retry.sh get python-deps
    # Download bender
    - make bender
    # Update opcodes
    - make update_opcodes
    # Compile the binaries
    - cd hw/system/spatz_cluster
    - make sw.vsim SPATZ_CLUSTER_CFG=${cfg}.hjson -B
    # Run the test
    - cd sw/build/snRuntime
    - ${CTEST} --output-on-failure
  needs: ["tc-llvm", "tc-gcc", "python-deps"]
  parallel:
    matrix:
      - { cfg: spatz_cluster.default.dram }
      - { cfg: spatz_cluster.smallvrf.dram }
      - { cfg: spatz_cluster.doublebw.dram }

snRuntime-test-vcs:
  stage: test
  script:
    # Download LLVM, GCC, and Python deps
    - $CI_PROJECT_DIR/util/memora_retry.sh get tc-llvm
    - $CI_PROJECT_DIR/util/memora_retry.sh get tc-riscv-gcc
    - $CI_PROJECT_DIR/util/memora_retry.sh get python-deps
    # Download bender
    - make bender
    # Update opcodes
    - make update_opcodes
    # Compile the binaries
    - cd hw/system/spatz_cluster
    - ${VCS} make sw.vcs SPATZ_CLUSTER_CFG=${cfg}.hjson -B
    # Run the test
    - cd sw/build/snRuntime
    - ${CTEST} --output-on-failure
  needs: ["tc-llvm", "tc-gcc", "python-deps"]
  parallel:
    matrix:
      - { cfg: spatz_cluster.default.dram }
      - { cfg: spatz_cluster.smallvrf.dram }
      - { cfg: spatz_cluster.doublebw.dram }

snRuntime-test-vlt:
  stage: test
  script:
    # Download LLVM, GCC, Verilator, and Python deps
    - $CI_PROJECT_DIR/util/memora_retry.sh get tc-llvm
    - $CI_PROJECT_DIR/util/memora_retry.sh get tc-riscv-gcc
    - $CI_PROJECT_DIR/util/memora_retry.sh get verilator
    - $CI_PROJECT_DIR/util/memora_retry.sh get python-deps
    # Download bender
    - make bender
    # Update opcodes
    - make update_opcodes
    # Compile the binaries
    - cd hw/system/spatz_cluster
    - make sw.vlt SPATZ_CLUSTER_CFG=${cfg}.hjson -B
    # Run the test
    - cd sw/build/snRuntime
    - ${CTEST} --output-on-failure
  needs: ["tc-llvm", "tc-gcc", "verilator", "python-deps"]
  parallel:
    matrix:
      - { cfg: spatz_cluster.default.dram }
      - { cfg: spatz_cluster.smallvrf.dram }
      - { cfg: spatz_cluster.doublebw.dram }

# RISC-V unit tests
riscvTests-test-vlt:
  stage: test
  script:
    # Download LLVM, GCC, Verilator, and Python deps
    - $CI_PROJECT_DIR/util/memora_retry.sh get tc-llvm
    - $CI_PROJECT_DIR/util/memora_retry.sh get tc-riscv-gcc
    - $CI_PROJECT_DIR/util/memora_retry.sh get verilator
    - $CI_PROJECT_DIR/util/memora_retry.sh get python-deps
    # Download bender
    - make bender
    # Update opcodes
    - make update_opcodes
    # Compile the binaries
    - cd hw/system/spatz_cluster
    - ${VCS} make sw.vlt SPATZ_CLUSTER_CFG=${cfg}.hjson -B
    # Run the test
    - cd sw/build/riscvTests
    - ${CTEST} --output-on-failure -j4
  needs: ["tc-llvm", "tc-gcc", "verilator", "python-deps"]
  parallel:
    matrix:
      - { cfg: spatz_cluster.default.dram }
      - { cfg: spatz_cluster.smallvrf.dram }
      - { cfg: spatz_cluster.32b.dram }
      - { cfg: spatz_cluster.doublebw.dram }

# Spatz tests
spatzBenchmarks-test-vlt:
  stage: test
  script:
    # Download LLVM, GCC, Verilator, and Python deps
    - $CI_PROJECT_DIR/util/memora_retry.sh get tc-llvm
    - $CI_PROJECT_DIR/util/memora_retry.sh get tc-riscv-gcc
    - $CI_PROJECT_DIR/util/memora_retry.sh get verilator
    - $CI_PROJECT_DIR/util/memora_retry.sh get python-deps
    # Download bender
    - make bender
    # Update opcodes
    - make update_opcodes
    # Compile the binaries
    - cd hw/system/spatz_cluster
    - ${VCS} make sw.vlt SPATZ_CLUSTER_CFG=${cfg}.hjson -B
    # Run the test
    - cd sw/build/spatzBenchmarks
    - ${CTEST} --verbose
  needs: ["tc-llvm", "tc-gcc", "verilator", "python-deps"]
  parallel:
    matrix:
      - { cfg: spatz_cluster.default.dram }
      - { cfg: spatz_cluster.smallvrf.dram }
      - { cfg: spatz_cluster.32b.dram }
      - { cfg: spatz_cluster.doublebw.dram }
