# Copyright 2021 ETH Zurich and University of Bologna.
# Licensed under the Apache License, Version 2.0, see LICENSE for details.
# SPDX-License-Identifier: Apache-2.0

# Author: Matheus Cavalcante, ETH Zurich

variables:
  GIT_SUBMODULE_STRATEGY: none
  ROOT_DIR: '$CI_PROJECT_DIR'
  APPS: "tests"
  OBJCACHE: ''
  RISCV_WARNINGS: '-Werror'
  CMAKE: 'cmake'
  CTEST: 'ctest'

workflow:
  rules:
    - if: $CI_MERGE_REQUEST_ID
    - if: $CI_COMMIT_TAG
    - if: $CI_COMMIT_REF_NAME

before_script:
  - source util/chips-it-env.sh
  - make update_opcodes

stages:
  - lint
  - test
  - benchmark

##########
#  Lint  #
##########

# Code style test
code-style:
  stage: lint
  script:
    - ./util/lint.sh

###########
#  Tests  #
###########

.sim-test:
  stage: test
  script:
    - cd hw/system/spatz_cluster
    - make ${SW_TARGET} SPATZ_CLUSTER_CFG=${cfg} -B
    - cd sw/build/${SUITE}
    - ${CTEST} ${CTEST_ARGS}

# Runtime tests
snRuntime-test-vsim:
  extends: .sim-test
  variables:
    SW_TARGET: sw.vsim
    SUITE: snRuntime
    CTEST_ARGS: '--output-on-failure'
  parallel:
    matrix:
      - { cfg: [default, smallvrf, doublebw] }

snRuntime-test-vcs:
  extends: .sim-test
  variables:
    SW_TARGET: sw.vcs
    SUITE: snRuntime
    CTEST_ARGS: '--output-on-failure'
  parallel:
    matrix:
      - { cfg: [default, smallvrf, doublebw] }

# RISC-V unit tests
riscvTests-test-vsim:
  extends: .sim-test
  variables:
    SW_TARGET: sw.vsim
    SUITE: riscvTests
    CTEST_ARGS: '--output-on-failure -j4'
  parallel:
    matrix:
      - { cfg: [default, smallvrf, 32b, doublebw] }

# Spatz tests
spatzBenchmarks-test-vsim:
  extends: .sim-test
  variables:
    SW_TARGET: sw.vsim
    SUITE: spatzBenchmarks
    CTEST_ARGS: '--verbose'
  parallel:
    matrix:
      - { cfg: [default, smallvrf, 32b, doublebw] }

spatzBenchmarks-ventaglio-test-vsim:
  extends: .sim-test
  variables:
    SW_TARGET: sw.vsim
    SUITE: spatzBenchmarks
    CTEST_ARGS: '--verbose -R spatzBenchmarks-rtl-sp-SpM'
  parallel:
    matrix:
      - { cfg: [ventaglio] }