#!/usr/bin/env python3
# Copyright 2026 ETH Zurich and University of Bologna.
# Licensed under the Apache License, Version 2.0, see LICENSE for details.
# SPDX-License-Identifier: Apache-2.0
#
# Author: Pei-Yu Lin <peilin@ethz.ch>
#
#
# Usage:
#   python3 script/gen_data.py -c script/matmul_64_64_64.json
#
# Output:
#   data/data_{M}_{N}_{K}.h
#
# The config JSON must provide: M, N, K.
# Optional field: seed (default 42).

import argparse
import pathlib

import hjson
import numpy as np
import torch

def array_to_cstr_f32(arr: np.ndarray) -> str:
    """Flat float32 array → C brace-initializer with 'f' suffix."""
    return "{" + ", ".join(repr(float(x)) + "f" for x in arr.flat) + "}"

def array_to_cstr_f16(arr: np.ndarray) -> str:
    """Flat float16 array → C brace-initializer for __fp16 arrays."""
    return "{" + ", ".join(repr(float(x)) for x in arr.flat) + "}"

def main():
    parser = argparse.ArgumentParser(
        description="Generate FP16xFP16->FP32 VME GEMM benchmark data header"
    )
    parser.add_argument(
        "-c", "--cfg",
        type=pathlib.Path,
        required=True,
        help="JSON/HJSON config file (e.g. script/matmul_64_64_64.json)",
    )
    args = parser.parse_args()

    with args.cfg.open() as f:
        param = hjson.loads(f.read())

    M    = int(param["M"])
    N    = int(param["N"])
    K    = int(param["K"])
    seed = int(param.get("seed", 42))

    torch.manual_seed(seed)

    A = torch.randn((M, K), dtype=torch.float32).to(torch.float16)
    B = torch.randn((K, N), dtype=torch.float32).to(torch.float16)
    C = (A.to(torch.float32) @ B.to(torch.float32)).numpy()
    A = A.numpy()
    B = B.numpy()

    # One 64-byte register slot per FP16 K row (VLEN=512, TE=16).
    # An e32,m8 load fills eight registers. tk=2 pairs register r with r+4,
    # so a group reduces K pairs (0,4), (1,5), (2,6), (3,7).
    TW16 = 16
    assert K >= 24 and K % 8 == 0
    assert M % TW16 == 0 and N % TW16 == 0
    A_pack = np.zeros((M // TW16, K, 2 * TW16), dtype=np.float16)
    B_pack = np.zeros((N // TW16, K, 2 * TW16), dtype=np.float16)
    A_pack[:, :, :TW16] = A.reshape(M // TW16, TW16, K).transpose(0, 2, 1)
    B_pack[:, :, :TW16] = B.reshape(K, N // TW16, TW16).transpose(1, 0, 2)

    lines = [
        "// Copyright 2026 ETH Zurich and University of Bologna.",
        "// Licensed under the Apache License, Version 2.0, see LICENSE for details.",
        "// SPDX-License-Identifier: Apache-2.0",
        "//",
        "// Author: Pei-Yu Lin <peilin@ethz.ch>",
        "//",
        "// Auto-generated by script/gen_data.py — do not edit by hand.",
        "",
        '#include "layer.h"',
        "",
        "const matmul_layer matmul_l = {",
        f"    .M  = {M},",
        f"    .N  = {N},",
        f"    .K  = {K},",
        "};",
        "",
        "// C[M*N] row-major fp32 golden reference, C = A*B",
        f'static float Cref_dram[{M}*{N}] __attribute__((section(".data"))) =',
        array_to_cstr_f32(C) + ";",
        "",
        "",
        "// A_pack[m_tile][k][32]: 16 FP16 values, then 16 zero padding values.",
        "// Eight 64-byte slots are loaded together by one e32,m8 vle32.v.",
        "// tk=2 uses K pairs (0,4), (1,5), (2,6), (3,7) within each group.",
        f'static __fp16 Apack_dram[2*{K}*{M}] __attribute__((section(".data"), aligned(64))) =',
        array_to_cstr_f16(A_pack) + ";",
        "",
        "",
        "// B_pack[n_tile][k][32], with the same zero-padded register layout.",
        f'static __fp16 Bpack_dram[2*{K}*{N}] __attribute__((section(".data"), aligned(64))) =',
        array_to_cstr_f16(B_pack) + ";",
        "",
    ]

    out_dir = pathlib.Path(__file__).parent.parent / "data"
    out_dir.mkdir(parents=True, exist_ok=True)
    out_file = out_dir / f"data_{M}_{N}_{K}.h"

    with out_file.open("w") as f:
        f.write("\n".join(lines))

    print(f"Written: {out_file}")

if __name__ == "__main__":
    main()
