#!/usr/bin/env python3
# Copyright 2026 ETH Zurich and University of Bologna.
# Licensed under the Apache License, Version 2.0, see LICENSE for details.
# SPDX-License-Identifier: Apache-2.0
#
# Author: Pei-Yu Lin <peilin@ethz.ch>
#
#
# Usage:
#   python3 script/gen_data.py -c script/matmul_64_64_64.json
#
# Output:
#   data/data_{M}_{N}_{K}.h
#
# The config JSON must provide: M, N, K.
# Optional field: seed (default 42).

import argparse
import pathlib

import hjson
import numpy as np
import torch

def array_to_cstr_f32(arr: np.ndarray) -> str:
    """Flat float32 array → C brace-initializer with 'f' suffix."""
    return "{" + ", ".join(repr(float(x)) + "f" for x in arr.flat) + "}"

def array_to_cstr_f16(arr: np.ndarray) -> str:
    """Flat float16 array → C brace-initializer for __fp16 arrays."""
    return "{" + ", ".join(repr(float(x)) for x in arr.flat) + "}"

def main():
    parser = argparse.ArgumentParser(
        description="Generate FP16xFP16->FP32 VME GEMM benchmark data header"
    )
    parser.add_argument(
        "-c", "--cfg",
        type=pathlib.Path,
        required=True,
        help="JSON/HJSON config file (e.g. script/matmul_64_64_64.json)",
    )
    args = parser.parse_args()

    with args.cfg.open() as f:
        param = hjson.loads(f.read())

    M    = int(param["M"])
    N    = int(param["N"])
    K    = int(param["K"])
    seed = int(param.get("seed", 42))

    torch.manual_seed(seed)

    A = torch.randn((M, K), dtype=torch.float32).to(torch.float16)
    B = torch.randn((K, N), dtype=torch.float32).to(torch.float16)
    C = (A.to(torch.float32) @ B.to(torch.float32)).numpy()
    A = A.numpy()
    B = B.numpy()

    # Contiguous K-pair packing for tk=2.
    TK = 2
    TW16 = 16
    assert K % TK == 0
    assert M % TW16 == 0 and N % TW16 == 0
    # A_pack[m_tile, k_group, slice, col] = A[m_tile*TW + col, 2*kg + slice]
    A_pack = (A.reshape(M // TW16, TW16, K // TK, TK)   # (mt, col, kg, slice)
                .transpose(0, 2, 3, 1)              # (mt, kg, slice, col)
                .copy())
    B_pack = (B.reshape(K // TK, TK, N // TW16, TW16)   # (kg, slice, nt, col)
                .transpose(2, 0, 1, 3)              # (nt, kg, slice, col)
                .copy())

    lines = [
        "// Copyright 2026 ETH Zurich and University of Bologna.",
        "// Licensed under the Apache License, Version 2.0, see LICENSE for details.",
        "// SPDX-License-Identifier: Apache-2.0",
        "//",
        "// Author: Pei-Yu Lin <peilin@ethz.ch>",
        "//",
        "// Auto-generated by script/gen_data.py — do not edit by hand.",
        "",
        '#include "layer.h"',
        "",
        "const matmul_layer matmul_l = {",
        f"    .M  = {M},",
        f"    .N  = {N},",
        f"    .K  = {K},",
        "};",
        "",
        "// C[M*N] row-major fp32 golden reference, C = A*B",
        f'static float Cref_dram[{M}*{N}] __attribute__((section(".data"))) =',
        array_to_cstr_f32(C) + ";",
        "",
        "",
        "// Contiguous K-row packing for the tk=2 FP16 kernel.",
        "// A_pack[m_tile][k_pair][slice][col], slice-major so each tk=2 pair",
        "// is contiguous; each vle16.v loads one 16-element K row.",
        "// pair ptr for (m_tile mt, pair g) = Apack_dram + (mt*(K/2)+g)*32.",
        f'static __fp16 Apack_dram[{K}*{M}] __attribute__((section(".data"))) =',
        array_to_cstr_f16(A_pack) + ";",
        "",
        "",
        "// B_pack[n_tile][k_pair][slice][col]; pair ptr for (n_tile nt, pair g)",
        "// = Bpack_dram + (nt*(K/2)+g)*32.",
        f'static __fp16 Bpack_dram[{K}*{N}] __attribute__((section(".data"))) =',
        array_to_cstr_f16(B_pack) + ";",
        "",
    ]

    out_dir = pathlib.Path(__file__).parent.parent / "data"
    out_dir.mkdir(parents=True, exist_ok=True)
    out_file = out_dir / f"data_{M}_{N}_{K}.h"

    with out_file.open("w") as f:
        f.write("\n".join(lines))

    print(f"Written: {out_file}")

if __name__ == "__main__":
    main()
