#!/usr/bin/env python3

import argparse
import pathlib

import numpy as np


TILE_DIM = 16
K_CHUNK = 128


def c_array_f16(array: np.ndarray) -> str:
    return "{" + ", ".join(repr(float(x)) for x in array.flat) + "}"


def c_array_f32(array: np.ndarray) -> str:
    return "{" + ", ".join(repr(float(x)) + "f" for x in array.flat) + "}"


def matmul_ref_tew16(a: np.ndarray, b: np.ndarray) -> np.ndarray:
    """Model FP16 accumulation followed by the software panel reduction."""
    result = np.zeros((a.shape[0], b.shape[1]), dtype=np.float32)
    for k0 in range(0, a.shape[1], K_CHUNK):
        panel = np.zeros(result.shape, dtype=np.float16)
        for k in range(k0, min(k0 + K_CHUNK, a.shape[1])):
            product = (a[:, k, None].astype(np.float32) *
                       b[k, None, :].astype(np.float32))
            panel = (panel.astype(np.float32) + product).astype(np.float16)
        result += panel.astype(np.float32)
    return result


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description="Generate packed TEW16/SEW16 matmul operands")
    parser.add_argument("--m", type=int)
    parser.add_argument("--n", type=int)
    parser.add_argument("--k", type=int)
    parser.add_argument("--seed", type=int, default=42)
    parser.add_argument("--output", type=pathlib.Path)
    parser.add_argument("-c", "--config", type=pathlib.Path)
    args = parser.parse_args()

    if args.config is not None:
        try:
            import hjson
        except ImportError as exc:
            raise RuntimeError("hjson is required when --config is used") from exc
        with args.config.open() as config_file:
            config = hjson.load(config_file)
        args.m = int(config["M"])
        args.n = int(config["N"])
        args.k = int(config["K"])
        args.seed = int(config.get("seed", args.seed))

    if args.m is None or args.n is None or args.k is None:
        parser.error("provide --m, --n, and --k, or use --config")
    if min(args.m, args.n, args.k) <= 0:
        parser.error("M, N, and K must all be positive")

    if args.output is None:
        app_dir = pathlib.Path(__file__).resolve().parent.parent
        args.output = app_dir / "data" / f"data_{args.m}_{args.n}_{args.k}.h"
    return args


def main() -> None:
    args = parse_args()
    m_tiles = (args.m + TILE_DIM - 1) // TILE_DIM
    n_tiles = (args.n + TILE_DIM - 1) // TILE_DIM

    rng = np.random.default_rng(args.seed)
    a = rng.standard_normal((args.m, args.k), dtype=np.float32).astype(np.float16)
    b = rng.standard_normal((args.k, args.n), dtype=np.float32).astype(np.float16)
    cref = matmul_ref_tew16(a, b)

    a_padded = np.zeros((m_tiles * TILE_DIM, args.k), dtype=np.float16)
    b_padded = np.zeros((args.k, n_tiles * TILE_DIM), dtype=np.float16)
    a_padded[:args.m, :args.k] = a
    b_padded[:args.k, :args.n] = b

    # Both operands are tile-major and K-major. Each K step has 16 physical
    # lanes; tm/tn select the valid lanes in the final M/N tile.
    apack = a_padded.reshape(m_tiles, TILE_DIM, args.k)
    apack = apack.transpose(0, 2, 1).copy()
    bpack = b_padded.reshape(args.k, n_tiles, TILE_DIM)
    bpack = bpack.transpose(1, 0, 2).copy()

    text = f'''// Auto-generated by tew16/fp16-matmul-vtse/script/gen_data.py.
#include "layer.h"

static const vme_matmul_layer matmul_l = {{
    .M = {args.m}, .N = {args.n}, .K = {args.k},
}};

static const float Cref_dram[{args.m * args.n}]
    __attribute__((section(".dram"), aligned(64))) = {c_array_f32(cref)};

static const __fp16 Apack_dram[{m_tiles * TILE_DIM * args.k}]
    __attribute__((section(".dram"), aligned(64))) = {c_array_f16(apack)};

static const __fp16 Bpack_dram[{args.k * n_tiles * TILE_DIM}]
    __attribute__((section(".dram"), aligned(64))) = {c_array_f16(bpack)};
'''
    args.output.parent.mkdir(parents=True, exist_ok=True)
    args.output.write_text(text)
    print(f"Written: {args.output}")


if __name__ == "__main__":
    main()
